window.michelleSecrets = {
    el: [
        "💡 Το ήξερες; Το σύμβολο του ίσον (=) εφευρέθηκε το 1557 επειδή ένας μαθηματικός βαρέθηκε να γράφει συνέχεια 'είναι ίσο με'!",
        "🐾 Οι γάτες έχουν 32 μύες σε κάθε αυτί. Μπορώ να ακούσω κάθε λάθος πράξη σου! 😼",
        "💡 Ο αριθμός μηδέν (0) ανακαλύφθηκε στην Ινδία γύρω στον 5ο αιώνα. Πριν από αυτό, απλά άφηναν ένα κενό!",
        "🐾 Meow! Αν πολλαπλασιάσεις το 111.111.111 με τον εαυτό του, βγάζει 12345678987654321! 🤯",
        "💡 Όπως ακριβώς και στις εξισώσεις, έτσι και στη ζωή: ό,τι κάνεις στη μία πλευρά, πρέπει να το κάνεις και στην άλλη για να υπάρχει ισορροπία! ⚖️",
        "🐾 Η μύτη κάθε γάτας είναι μοναδική, σαν το ανθρώπινο δακτυλικό αποτύπωμα. Το ίδιο μοναδική είναι και η λύση μιας εξίσωσης!",
        "🐾 Αν προσπαθήσεις να διαιρέσεις με το μηδέν, το σύμπαν θα γεμίσει τριχόμπαλες! 🙀",
        "💡 Η αγαπημένη μου εξίσωση είναι: E = mc^meow 🐈",
        "🐾 Οι γάτες προσγειώνονται πάντα στα 4, ακριβώς όπως το x σε μια τέλεια εξίσωση! 🐾",
        "💡 Ποτέ μην ξεχνάς το πλην (-). Είναι σαν να ξεχνάς να με ταΐσεις. Καταστροφή! 😿",
        "🐾 Το ΕΚΠ δεν σημαίνει Εξαιρετικά Κομψός Πάνθηρας. Ελάχιστο Κοινό Πολλαπλάσιο είναι! 🐆",
        "💡 Ο αριθμός 'Pi' (π) γράφτηκε για πρώτη φορά με αυτό το σύμβολο το 1706 από τον William Jones.",
        "🐾 Ο εγκέφαλος μιας γάτας είναι κατά 90% όμοιος με τον ανθρώπινο. Γι' αυτό είμαστε τόσο καλοί στην Άλγεβρα!",
        "💡 Στα μαθηματικά, το 'Googol' είναι ο αριθμός 1 ακολουθούμενος από 100 μηδενικά. Από εκεί πήρε το όνομά της και η Google!",
        "🐾 Αν τα μαθηματικά ήταν ποντίκια, θα τα είχα πιάσει όλα! 🐭",
        "💡 Το κλάσμα 22/7 είναι η πιο συνηθισμένη προσέγγιση του π, αλλά δεν είναι ακριβές!",
        "🐾 Ο Ισαάκ Νεύτων εφηύρε την πόρτα για τις γάτες! Πώς αλλιώς θα έλυνε τις εξισώσεις του με την ησυχία του;",
        "💡 Το θεώρημα του Πυθαγόρα (a² + b² = c²) είναι ένα από τα παλαιότερα και πιο διάσημα θεωρήματα.",
        "🐾 Η Μισέλ μπορεί να τρέξει με 48 km/h! Αν αυτό δεν είναι εντυπωσιακή Φυσική, τότε τι είναι;",
        "💡 Η λέξη Άλγεβρα προέρχεται από το αραβικό 'al-jabr', που σημαίνει 'επανένωση σπασμένων μερών'.",
        "🐾 Αν κρύψεις ένα ποντίκι μέσα σε μια παρένθεση, πρέπει πρώτα να λύσεις την παρένθεση για να το βρεις! 🐭",
        "💡 Το 2 είναι ο μοναδικός άρτιος πρώτος αριθμός. Όλοι οι άλλοι είναι περιττοί!",
        "🐾 Το νιαούρισμα δημιουργήθηκε αποκλειστικά για να επικοινωνούν οι γάτες με τους ανθρώπους... και να ζητούν βοήθεια στις ασκήσεις! 😼",
        "💡 Ο Λεονάρντο Ντα Βίντσι χρησιμοποιούσε τη Χρυσή Τομή (1.618) για να ζωγραφίσει τα αριστουργήματά του.",
        "🐾 Σύμφωνα με τη φυσική των γατών, αν ένα ποτήρι είναι στο τραπέζι, πρέπει να πέσει στο πάτωμα! 🐾",
        "💡 Το 100 προέρχεται από την αρχαία λέξη 'hundrath', που δεν σήμαινε 100 αλλά 120!",
        "🐾 Οι γάτες κοιμούνται το 70% της ζωής τους. Το υπόλοιπο 30% λύνουν εξισώσεις... και τρώνε.",
        "💡 Η ακολουθία Fibonacci εμφανίζεται παντού στη φύση: στα λουλούδια, στα κοχύλια και... στις ουρές των γατών!",
        "🐾 Όπως ο νόμος της αδράνειας: Μια γάτα σε κίνηση θα παραμείνει σε κίνηση μέχρι να βρει φαγητό! 🍗",
        "💡 Στη γεωμετρία, το σχήμα που αποθηκεύει τον περισσότερο όγκο με τη λιγότερη επιφάνεια είναι η σφαίρα. Γι' αυτό οι γάτες κουλουριάζονται σαν μπάλες!"
    ],
    en: [
        "💡 Did you know? The equals sign (=) was invented in 1557 because a mathematician got tired of writing 'is equal to'!",
        "🐾 Cats have 32 muscles in each ear. I can hear every calculation mistake you make! 😼",
        "💡 The number zero (0) was discovered in India around the 5th century. Before that, they just left a blank space!",
        "🐾 Meow! If you multiply 111,111,111 by itself, you get 12345678987654321! 🤯",
        "💡 Just like in equations, in life: whatever you do to one side, you must do to the other to keep balance! ⚖️",
        "🐾 A cat's nose pad is unique, just like a human fingerprint. And just as unique as the solution to an equation!",
        "🐾 If you try to divide by zero, the universe will fill with hairballs! 🙀",
        "💡 My favorite equation is: E = mc^meow 🐈",
        "🐾 Cats always land on all 4s, just like x in a perfect equation! 🐾",
        "💡 Never forget the minus sign (-). It's like forgetting to feed me. A disaster! 😿",
        "🐾 LCM does not stand for Large Cat Meowing. It's Least Common Multiple! 🐆",
        "💡 The number 'Pi' (π) was first written with this symbol in 1706 by William Jones.",
        "🐾 A cat's brain is 90% similar to a human's. That's why we are so good at Algebra!",
        "💡 In math, a 'Googol' is the number 1 followed by 100 zeros. That's where Google got its name!",
        "🐾 If math problems were mice, I would have caught them all! 🐭",
        "💡 The fraction 22/7 is the most common approximation of pi, but it's not exact!",
        "🐾 Isaac Newton invented the cat flap! How else would he solve his equations in peace?",
        "💡 The Pythagorean theorem (a² + b² = c²) is one of the oldest and most famous theorems.",
        "🐾 Michelle can run at 48 km/h! If that's not impressive Physics, then what is?",
        "💡 The word Algebra comes from the Arabic 'al-jabr', meaning 'reunion of broken parts'.",
        "🐾 If you hide a mouse inside parentheses, you have to solve the parentheses first to find it! 🐭",
        "💡 2 is the only even prime number. All others are odd!",
        "🐾 Meowing was developed exclusively for cats to communicate with humans... and to ask for math help! 😼",
        "💡 Leonardo Da Vinci used the Golden Ratio (1.618) to paint his masterpieces.",
        "🐾 According to cat physics, if a glass is on the table, it must fall to the floor! 🐾",
        "💡 100 comes from the old Norse word 'hundrath', which meant 120, not 100!",
        "🐾 Cats sleep for 70% of their lives. The other 30% they solve equations... and eat.",
        "💡 The Fibonacci sequence appears everywhere in nature: in flowers, shells, and... cat tails!",
        "🐾 Like the law of inertia: A cat in motion will stay in motion until it finds food! 🍗",
        "💡 In geometry, the shape that stores the most volume with the least surface area is a sphere. That's why cats curl up like balls!"
    ],
    fr: [
        "💡 Le savais-tu ? Le signe égal (=) a été inventé en 1557 parce qu'un mathématicien en avait marre d'écrire 'est égal à' !",
        "🐾 Les chats ont 32 muscles dans chaque oreille. Je peux entendre toutes tes erreurs de calcul ! 😼",
        "💡 Le chiffre zéro (0) a été découvert en Inde vers le Ve siècle. Avant cela, on laissait simplement un espace vide !",
        "🐾 Miaou ! Si tu multiplies 111 111 111 par lui-même, tu obtiens 12345678987654321 ! 🤯",
        "💡 Tout comme dans les équations, dans la vie : ce que tu fais d'un côté, tu dois le faire de l'autre pour garder l'équilibre ! ⚖️",
        "🐾 La truffe d'un chat est unique, comme une empreinte digitale humaine. Tout aussi unique que la solution d'une équation !",
        "🐾 Si tu essaies de diviser par zéro, l'univers se remplira de boules de poils ! 🙀",
        "💡 Mon équation préférée est : E = mc^meow 🐈",
        "🐾 Les chats retombent toujours sur leurs 4 pattes, tout comme x dans une équation parfaite ! 🐾",
        "💡 N'oublie jamais le signe moins (-). C'est comme oublier de me nourrir. Une catastrophe ! 😿",
        "🐾 Le PPCM ne signifie pas Petit Puma Très Mignon. C'est le Plus Petit Commun Multiple ! 🐆",
        "💡 Le nombre 'Pi' (π) a été écrit pour la première fois avec ce symbole en 1706 par William Jones.",
        "🐾 Le cerveau d'un chat est similaire à 90 % à celui d'un humain. C'est pourquoi nous sommes si bons en algèbre !",
        "💡 En mathématiques, un 'Googol' est le chiffre 1 suivi de 100 zéros. C'est de là que Google tire son nom !",
        "🐾 Si les problèmes de maths étaient des souris, je les aurais tous attrapés ! 🐭",
        "💡 La fraction 22/7 est l'approximation la plus courante de pi, mais elle n'est pas exacte !",
        "🐾 Isaac Newton a inventé la chatière ! Comment sinon aurait-il pu résoudre ses équations en paix ?",
        "💡 Le théorème de Pythagore (a² + b² = c²) est l'un des théorèmes les plus anciens et les plus célèbres.",
        "🐾 Michelle peut courir à 48 km/h ! Si ce n'est pas de la physique impressionnante, alors qu'est-ce que c'est ?",
        "💡 Le mot Algèbre vient de l'arabe 'al-jabr', qui signifie 'réunion des parties brisées'.",
        "🐾 Si tu caches une souris entre des parenthèses, tu dois d'abord résoudre les parenthèses pour la trouver ! 🐭",
        "💡 2 est le seul nombre premier pair. Tous les autres sont impairs !",
        "🐾 Le miaulement a été développé exclusivement pour que les chats communiquent avec les humains... et demandent de l'aide en maths ! 😼",
        "💡 Léonard de Vinci a utilisé le nombre d'or (1,618) pour peindre ses chefs-d'œuvre.",
        "🐾 Selon la physique des chats, si un verre est sur la table, il doit tomber par terre ! 🐾",
        "💡 100 vient de l'ancien mot nordique 'hundrath', qui signifiait 120, pas 100 !",
        "🐾 Les chats dorment pendant 70 % de leur vie. Les 30 % restants, ils résolvent des équations... et mangent.",
        "💡 La suite de Fibonacci apparaît partout dans la nature : dans les fleurs, les coquillages et... les queues de chats !",
        "🐾 Comme la loi d'inertie : Un chat en mouvement restera en mouvement jusqu'à ce qu'il trouve de la nourriture ! 🍗",
        "💡 En géométrie, la forme qui stocke le plus de volume avec le moins de surface est une sphère. C'est pourquoi les chats se mettent en boule !"
    ],
    tr: [
        "💡 Biliyor muydun? Eşittir işareti (=) 1557'de icat edildi çünkü bir matematikçi 'eşittir' yazmaktan yorulmuştu!",
        "🐾 Kedilerin her kulağında 32 kas vardır. Yaptığın her hatayı duyabilirim! 😼",
        "💡 Sıfır (0) sayısı 5. yüzyılda Hindistan'da keşfedildi. Ondan önce sadece boşluk bırakıyorlardı!",
        "🐾 Miyav! 111.111.111'i kendisiyle çarparsan 12345678987654321 elde edersin! 🤯",
        "💡 Hayatta dengeyi korumak için bir tarafa ne yaparsan diğerine de aynısını yapmalısın! ⚖️",
        "🐾 Bir kedinin burnu insan parmak izi gibi benzersizdir. Bir denklemin çözümü kadar eşsizdir!",
        "🐾 Sıfıra bölmeye çalışırsan, evren tüy yumaklarıyla dolar! 🙀",
        "💡 En sevdiğim denklem: E = mc^miyav 🐈",
        "🐾 Kediler her zaman 4 ayak üstüne düşer, tıpkı mükemmel bir denklemdeki x gibi! 🐾",
        "💡 Eksi (-) işaretini asla unutma. Beni beslemeyi unutmak gibidir. Gerçek bir felaket! 😿",
        "🐾 EKOK, Ekstra Komik Orman Kedisi demek değildir. En Küçük Ortak Kat demektir! 🐆",
        "💡 'Pi' (π) sayısı ilk olarak 1706'da William Jones tarafından bu sembolle yazılmıştır.",
        "🐾 Bir kedinin beyni insan beynine %90 benzer. Bu yüzden Cebir'de çok iyiyiz!",
        "💡 Matematikte 'Googol', 1 rakamını takip eden 100 sıfırdan oluşur. Google adını buradan almıştır!",
        "🐾 Matematik problemleri fare olsaydı, hepsini yakalardım! 🐭",
        "💡 22/7 kesri pi'nin en yaygın yaklaşımıdır, ancak kesin değildir!",
        "🐾 Isaac Newton kedi kapısını icat etti! Yoksa denklemlerini nasıl huzur içinde çözebilirdi?",
        "💡 Pisagor teoremi (a² + b² = c²) en eski ve en ünlü teoremlerden biridir.",
        "🐾 Michelle 48 km/s hızla koşabilir! Bu etkileyici Fizik değilse nedir?",
        "💡 Cebir kelimesi, 'kırık parçaların yeniden birleşmesi' anlamına gelen Arapça 'al-jabr' kelimesinden gelir.",
        "🐾 Bir fareyi parantez içine saklarsan, onu bulmak için önce parantezleri çözmelisin! 🐭",
        "💡 2 tek çift asal sayıdır. Diğerlerinin hepsi tektir!",
        "🐾 Miyavlama, kedilerin insanlarla iletişim kurması ve matematik yardımı istemesi için özel olarak geliştirilmiştir! 😼",
        "💡 Leonardo Da Vinci başyapıtlarını çizerken Altın Oran'ı (1.618) kullandı.",
        "🐾 Kedi fiziğine göre masanın üzerinde bir bardak varsa o yere düşmelidir! 🐾",
        "💡 100, 100 değil 120 anlamına gelen eski İskandinav kelimesi 'hundrath'tan gelir!",
        "🐾 Kediler hayatlarının %70'ini uyuyarak geçirirler. Geri kalan %30'unda denklem çözerler... ve yemek yerler.",
        "💡 Fibonacci dizisi doğanın her yerinde karşımıza çıkar: çiçeklerde, deniz kabuklarında ve... kedi kuyruklarında!",
        "🐾 Eylemsizlik yasası gibi: Hareket halindeki bir kedi yemek bulana kadar hareket halinde kalır! 🍗",
        "💡 Geometride, en az yüzey alanıyla en fazla hacmi depolayan şekil küredir. Bu yüzden kediler top gibi kıvrılırlar!"
    ]
};
